// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_EZ_3d_cpp
List calc_EZ_3d_cpp(IntegerVector V1, IntegerVector V2, IntegerVector V3, NumericVector x_vals, NumericVector alpha_k, int n, int p, int w);
RcppExport SEXP _CoSparTA_calc_EZ_3d_cpp(SEXP V1SEXP, SEXP V2SEXP, SEXP V3SEXP, SEXP x_valsSEXP, SEXP alpha_kSEXP, SEXP nSEXP, SEXP pSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type V1(V1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type V2(V2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type V3(V3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_k(alpha_kSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_EZ_3d_cpp(V1, V2, V3, x_vals, alpha_k, n, p, w));
    return rcpp_result_gen;
END_RCPP
}
// calc_qz_sparse_cpp
NumericMatrix calc_qz_sparse_cpp(IntegerVector V1, IntegerVector V2, IntegerVector V3, NumericMatrix Elogl, NumericMatrix Elogf, NumericMatrix Elogw);
RcppExport SEXP _CoSparTA_calc_qz_sparse_cpp(SEXP V1SEXP, SEXP V2SEXP, SEXP V3SEXP, SEXP EloglSEXP, SEXP ElogfSEXP, SEXP ElogwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type V1(V1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type V2(V2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type V3(V3SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Elogl(EloglSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Elogf(ElogfSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Elogw(ElogwSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_qz_sparse_cpp(V1, V2, V3, Elogl, Elogf, Elogw));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CoSparTA_calc_EZ_3d_cpp", (DL_FUNC) &_CoSparTA_calc_EZ_3d_cpp, 8},
    {"_CoSparTA_calc_qz_sparse_cpp", (DL_FUNC) &_CoSparTA_calc_qz_sparse_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_CoSparTA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
