# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sparse Weighted Aggregation for Tensor EM
#'
#' @description
#' For a sparse 3-way tensor stored in coordinate format, computes the
#' rank-k sufficient statistics (row sums, column sums, slice sums) needed
#' for the EM update of factor matrices L, F, W. Replaces the dplyr
#' group-by approach in \code{calc_EZ_3d()}.
#'
#' @param V1 Integer vector of user (L-mode) indices (1-based).
#' @param V2 Integer vector of time (F-mode) indices (1-based).
#' @param V3 Integer vector of channel (W-mode) indices (1-based).
#' @param x_vals Numeric vector of observed counts at each nonzero position.
#' @param alpha_k Numeric vector of length \code{nnz}: the rank-k responsibility
#'   weights (alpha[, k]).
#' @param n Integer. Number of users (L-mode dimension).
#' @param p Integer. Number of time points (F-mode dimension).
#' @param w Integer. Number of channels (W-mode dimension).
#'
#' @return A named list with three numeric vectors:
#'   \item{rs}{Length-\code{n} vector: row sums (L-mode aggregation).}
#'   \item{cs}{Length-\code{p} vector: column sums (F-mode aggregation).}
#'   \item{zs}{Length-\code{w} vector: slice sums (W-mode aggregation).}
#'
#' @export
calc_EZ_3d_cpp <- function(V1, V2, V3, x_vals, alpha_k, n, p, w) {
    .Call(`_CxtEBTD_calc_EZ_3d_cpp`, V1, V2, V3, x_vals, alpha_k, n, p, w)
}

#' Sparse Softmax (Responsibility) Computation
#'
#' @description
#' Computes the softmax responsibility matrix alpha (nnz x K) at nonzero
#' positions of a sparse 3-way tensor, using the log-sum-exp trick for
#' numerical stability. Replaces the five-line R block:
#' \preformatted{
#'   alpha = Elogl[V1,] + Elogf[V2,] + Elogw[V3,]
#'   exp_offset = rowMaxs(alpha)
#'   alpha = alpha - outer(exp_offset, rep(1,K))
#'   alpha = exp(alpha)
#'   alpha = alpha / rowsums(alpha)
#' }
#'
#' @param V1 Integer vector of user (L-mode) indices (1-based), length nnz.
#' @param V2 Integer vector of time (F-mode) indices (1-based), length nnz.
#' @param V3 Integer vector of channel (W-mode) indices (1-based), length nnz.
#' @param Elogl Numeric matrix (n x K): expected log loadings for L-mode.
#' @param Elogf Numeric matrix (p x K): expected log loadings for F-mode.
#' @param Elogw Numeric matrix (w x K): expected log loadings for W-mode.
#'
#' @return A numeric matrix of size (nnz x K): the row-normalized softmax
#'   responsibilities at each nonzero position.
#'
#' @export
calc_qz_sparse_cpp <- function(V1, V2, V3, Elogl, Elogf, Elogw) {
    .Call(`_CxtEBTD_calc_qz_sparse_cpp`, V1, V2, V3, Elogl, Elogf, Elogw)
}

